language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
install:
  - pip install poetry
  - poetry install
script:
  - poetry run black --check .
  - poetry run pytest
  - poetry run flake8
  - poetry run mypy imapy
after_success:
  - poetry run codecov
deploy:
  provider: script
  script: poetry build && poetry publish
  on:
    tags: true
    python: "3.11"
