Delivered-To: imapy-test1@gmail.com
Received: by 10.140.19.240 with SMTP id 103csp801695qgh;
        Sat, 2 May 2015 06:46:03 -0700 (PDT)
X-Received: by 10.70.49.35 with SMTP id r3mr27398077pdn.22.1430574362579;
        Sat, 02 May 2015 06:46:02 -0700 (PDT)
Return-Path: <0000014d14e06a53-f4aba918-d982-4176-a3b2-62f764db79d3-000000@us-west-2.amazonses.com>
Received: from a27-71.smtp-out.us-west-2.amazonses.com (a27-71.smtp-out.us-west-2.amazonses.com. [54.240.27.71])
        by mx.google.com with ESMTPS id rf2si12166868pbc.225.2015.05.02.06.46.01
        for <imapy-test1@gmail.com>
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Sat, 02 May 2015 06:46:02 -0700 (PDT)
Received-SPF: pass (google.com: domain of 0000014d14e06a53-f4aba918-d982-4176-a3b2-62f764db79d3-000000@us-west-2.amazonses.com designates 54.240.27.71 as permitted sender) client-ip=54.240.27.71;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of 0000014d14e06a53-f4aba918-d982-4176-a3b2-62f764db79d3-000000@us-west-2.amazonses.com designates 54.240.27.71 as permitted sender) smtp.mail=0000014d14e06a53-f4aba918-d982-4176-a3b2-62f764db79d3-000000@us-west-2.amazonses.com;
       dkim=pass header.i=@dropboxmail.com;
       dmarc=pass (p=REJECT dis=NONE) header.from=dropboxmail.com
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=7v7vs6w47njt4pimodk5mmttbegzsi6n; d=amazonses.com; t=1430574361;
	h=Content-Type:MIME-Version:From:To:CC:Subject:Date:Message-ID:Feedback-ID;
	bh=L3G8Vfx5HjdDawt2Da3isvUd6b/WRt0mGQXsuisRFyI=;
	b=e8NiiXfIeaN513nefwFV5z2MOZk0QWVxXOEpG2Jw+cWk17D4hxBXcpaBJP9oPwGb
	/Wi8c9LJDR72Zi8vSIpb1fcacpwVUSjLeH92fed47FJEy7Vy8EwCpy9qk/Ua815cBrv
	pPxKxxjuv+Gkvj2NgG4DPUcmKQMk1iDae+IguID0=
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=rmhucqoopiqyt3zo5rxb2jz6js3iyytt; d=dropboxmail.com;
	t=1430574361;
	h=Content-Type:MIME-Version:From:To:CC:Subject:Date:Message-ID;
	bh=CqHBsqcY0QileMWaILjPjc0VloUWbjr04tzaWBA/k1s=;
	b=JOm7U1DDPypgoMuLaUJiMIC04c7tHkDoCliikUmXlT4Eoq0xoRw1VxhM6BTeoBQo
	asaowLh3Kpx6kcOaqrgXG9jQUOb2p0MSDpzW1vZFH/kBRGxAzF1ZGFZs/vy6MkTVNfp
	toxQv6hNkCfcfqFtUSVRFhdXs2HsG649AwkA7Hfk=
Content-Type: multipart/alternative;
 boundary="===============1642230754920957684=="
MIME-Version: 1.0
From: Dropbox <no-reply@dropboxmail.com>
To: imapy-test1@gmail.com
CC: 
Subject: =?utf-8?q?Update=3A_Changes_to_better_serve_our_users_around_the_world?=
Date: Sat, 2 May 2015 13:46:01 +0000
Message-ID: <0000014d14e06a53-f4aba918-d982-4176-a3b2-62f764db79d3-000000@us-west-2.amazonses.com>
X-Dropbox-Message-ID: 1129471313071651627
X-SES-Outgoing: 2014.05.02-54.240.27.71
Feedback-ID: 1.us-west-2.QMExmXOQO+hfAVykUZJjA9h63TUIipok4C8L+okvtbc=:AmazonSES

--===============1642230754920957684==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable

Hi there,

If you're a user living outside of North America (U.S., Canada, Mexico), we=
're updating our Terms of Service to better serve you and the growing numbe=
r of Dropbox users around the world. These changes include the fact that we=
'll be providing our services (including Dropbox, Dropbox for Business, Car=
ousel, and Mailbox) to you via Dropbox Ireland starting on June 1, 2015. Pl=
ease note that none of our services or features are changing as a result of=
 this. You can read the updated terms at https://www.dropbox.com/l/eJ3aRDHS=
aGzBYDo10Aif3h/terms?text=3D1.

Have questions about these changes? Visit our Help Center[1] .

Thanks for using Dropbox!
The Dropbox Team

[1]: https://www.dropbox.com/123
--===============1642230754920957684==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w=
3.org/TR/REC-html40/loose.dtd">
<html xmlns=3D"http://www.w3.org/1999/xhtml"><head><meta content=3D"text/ht=
ml; charset=3Dutf-8" http-equiv=3D"Content-Type"><style>
        @font-face {
            font-family: "proxima_nova";
            src: url("https://www.dropbox.com/static/fonts/proximanova/prox=
ima-nova-regular.otf") format("opentype");
            font-weight: normal;
            font-style: normal;
        }
        a {
            color: #007ee6;
            text-decoration: none;
        }
        </style></head><body style=3D"padding: 0; width: 100% !important; -=
webkit-text-size-adjust: 100%; margin: 0; -ms-text-size-adjust: 100%;" marg=
inheight=3D"0" marginwidth=3D"0"><center><table cellpadding=3D"8" cellspaci=
ng=3D"0" style=3D"*width: 540px; padding: 0; width: 100% !important; backgr=
ound: #ffffff; margin: 0; background-color: #ffffff;" border=3D"0"><tr><td =
valign=3D"top">
<table cellpadding=3D"0" cellspacing=3D"0" style=3D"border-radius: 4px; -we=
bkit-border-radius: 4px; border: 1px #dceaf5 solid; -moz-border-radius: 4px=
;" border=3D"0" align=3D"center"><tr><td colspan=3D"3" height=3D"6"></td></=
tr><tr style=3D"line-height: 0px;"><td width=3D"100%" style=3D"font-size: 0=
px;" align=3D"center" height=3D"1"><img width=3D"40px" style=3D"max-height:=
 73px; width: 40px; *width: 40px; *height: 73px;" alt=3D"" src=3D"https://w=
ww.dropbox.com/static/images/emails/glyph/glyph_34@2x.png"></td></tr><tr><t=
d><table cellpadding=3D"0" cellspacing=3D"0" style=3D"line-height: 25px;" b=
order=3D"0" align=3D"center"><tr><td colspan=3D"3" height=3D"30"></td></tr>=
<tr><td width=3D"36"></td>
<td width=3D"454" align=3D"left" style=3D"color: #444444; border-collapse: =
collapse; font-size: 11pt; font-family: proxima_nova, 'Open Sans', 'Lucida =
Grande', 'Segoe UI', Arial, Verdana, 'Lucida Sans Unicode', Tahoma, 'Sans S=
erif'; max-width: 454px;" valign=3D"top">Hi there,<br><br>If you're a user =
living outside of North America (U.S., Canada, Mexico), we're updating our =
Terms of Service to better serve you and the growing number of Dropbox user=
s around the world. These changes include the fact that we'll be providing =
our services (including Dropbox, Dropbox for Business, Carousel, and Mailbo=
x) to you via Dropbox Ireland starting on June 1, 2015. Please note that no=
ne of our services or features are changing as a result of this. You can re=
ad the updated terms at https://www.dropbox.com/terms.<br><br>   Have quest=
ions about these changes? Visit our <a href=3D"https://www.dropbox.com/l/9i=
HgtW9Byn59kBzJw0nnDw/help/9063">Help Center</a>.<br><br>Thanks for using Dr=
opbox!<br>The Dropbox Team</td>
<td width=3D"36"></td>
</tr><tr><td colspan=3D"3" height=3D"36"></td></tr></table></td></tr></tabl=
e><table cellpadding=3D"0" cellspacing=3D"0" align=3D"center" border=3D"0">=
<tr><td height=3D"10"></td></tr><tr><td style=3D"padding: 0; border-collaps=
e: collapse;"><table cellpadding=3D"0" cellspacing=3D"0" align=3D"center" b=
order=3D"0"><tr style=3D"color: #a8b9c6; font-size: 11px; font-family: prox=
ima_nova, 'Open Sans', 'Lucida Grande', 'Segoe UI', Arial, Verdana, 'Lucida=
 Sans Unicode', Tahoma, 'Sans Serif'; -webkit-text-size-adjust: none;"><td =
width=3D"400" align=3D"left"></td>
<td width=3D"128" align=3D"right">&#169; 2015 Dropbox</td>
</tr></table></td></tr></table></td></tr></table></center></body></html><im=
g width=3D"1" src=3D"https://www.dropbox.com/l/PiXFvnjLe7RUZ4F5NdprqE" heig=
ht=3D"1" />
--===============1642230754920957684==--
