Delivered-To: imaptest@gmail.com
Received: by 10.25.14.6 with SMTP id 6csp980528lfo;
        Tue, 21 Apr 2015 22:00:38 -0700 (PDT)
X-Received: by 10.170.79.65 with SMTP id v62mr22599487ykv.70.1429678837321;
        Tue, 21 Apr 2015 22:00:37 -0700 (PDT)
Return-Path: <b054781bc96imaptest=gmail.com@bounce.twitter.com>
Received: from spring-chicken-bh.twitter.com (spring-chicken-bh.twitter.com. [199.16.156.173])
        by mx.google.com with ESMTPS id y65si2142954yhc.115.2015.04.21.22.00.36
        for <imaptest@gmail.com>
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 21 Apr 2015 22:00:37 -0700 (PDT)
Received-SPF: pass (google.com: domain of b054781bc96imaptest=gmail.com@bounce.twitter.com designates 199.16.156.173 as permitted sender) client-ip=199.16.156.173;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of b054781bc96imaptest=gmail.com@bounce.twitter.com designates 199.16.156.173 as permitted sender) smtp.mail=b054781bc96imaptest=gmail.com@bounce.twitter.com;
       dkim=pass header.i=@twitter.com;
       dmarc=pass (p=REJECT dis=NONE) header.from=twitter.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=twitter.com;
	s=dkim-201406; t=1429678836;
	bh=aVt5QSlbFeLJHkk/uyq90A6OVp25vCG7f4MYUdSeSSA=;
	h=Date:From:To:Subject:MIME-Version:Content-Type:List-Unsubscribe:
	 Message-ID;
	b=RMCE2MgPiRgIpSto/ufdnkbP0H2hd/sR3odN+O/fxeAZBCaFyi7i25eq5sjz5g4te
	 pE3c42gxE99cqoKL3ga5i0fDYa5+nalGIUntd8pKNEnz64XEr1WygtKZijKxW0Wbj6
	 KIPRh3UQulMQ5aO5++sV+zzRTz6XnmVqS8LBxJMabEiJGYxszAYgQOsecMscAnXgcg
	 aYW/V3TRJU975fx6ryh/by4rklXToXJdA/tlJNj1jB6E3YLQKCb/FGkKVZY1doOMgO
	 pgdsgSrP5dHOGsj4Wmm4H7dgdu93E34YAbaypLql6Xw9f5Gmr/VFNFW1OFQ/E5C8tm
	 xuQFBjAK/YtsA==
X-MSFBL: eyJ1IjoiY29yYmVub3ZAZ21haWwuY29tQDIzQDk1MjE2MDg5QDBAYmQ5MjNhMTI1
	NTRjM2RhZjY4OWMyNDE3NTVhOTE4YjUxZDZkNmJhOSIsImIiOiJhdGxhLWJkby0y
	NC1zcjEtRXZlcnl0aGluZy4xOTMiLCJyIjoiY29yYmVub3ZAZ21haWwuY29tIiwi
	ZyI6IkV2ZXJ5dGhpbmcifQ==
Date: Wed, 22 Apr 2015 05:00:36 +0000
From: =?UTF-8?Q?=D0=9D=D0=B0=D0=B4=D0=B5=D0=B6=D0=B4=D0=B0?= =?UTF-8?Q?_=D0=94=D1=80=D0=B0=D0=BD=D0=B8=D0=BD=D0=B0?= =?UTF-8?Q?fS_=28via_Twitter=29?= <notify@twitter.com>
To: Vlad <imaptest@gmail.com>
Subject: =?UTF-8?Q?=D0=9D=D0=B0=D0=B4=D0=B5=D0=B6=D0=B4=D0=B0?=
 =?UTF-8?Q?_=D0=94=D1=80=D0=B0=D0=BD=D0=B8=D0=BD=D0=B0?=
 =?UTF-8?Q?fS_(@dranina73)_?= =?UTF-8?Q?is_now_following_you_on_Twitter!?=
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_43710565_1338727258.1429678836363"
List-Unsubscribe: https://twitter.com/
Feedback-ID: 154a162f28f18f41:154a162f28f18f41:none:twitterESP
Message-ID: <83.67.14700.4FA27355@twitter.com>

------=_Part_43710565_1338727258.1429678836363
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Vlad,
You have a new follower on Twitter.

------------------------

=D0=9D=D0=B0=D0=B4=D0=B5=D0=B6=D0=B4=D0=B0 =D0=94=D1=80=D0=B0=D0=BD=D0=B8=
=D0=BD=D0=B0fS
@dranina73
I are excited about backpacking throughout the world
Tulsa OK


Follow:
https://twitter.com/dranina73


--=20

Forgot your Twitter password? Get instructions on how to reset it:
https://twitter.com/account/resend_password

You can also unsubscribe from these emails or change your notification sett=
ings:
https://twitter.com/123
https://twitter.com/settings/notifications

Need help?
https://support.twitter.com

If you received this message in error and did not sign up for a Twitter acc=
ount, click on the url below:
https://twitter.com/account/not_my_account/imaptest/
------=_Part_43710565_1338727258.1429678836363
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/htm=
l4/strict.dtd">
<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8" />
<meta name=3D"viewport" content=3D"width=3Ddevice-width, minimum-scale=3D1.=
0, maximum-scale=3D1.0, user-scalable=3D0" />
<meta name=3D"apple-mobile-web-app-capable" content=3D"yes" />
<style type=3D"text/css">
@media only screen and (max-device-width: 480px) {
table[class=3Douter] .global-width-670-to-320 {
width: 320px !important;
}
table[class=3Douter] .global-width-520-to-320 {
width: 320px !important;
}
table[class=3Douter] .global-width-500-to-300 {
width: 300px !important;
}
table[class=3Douter] .global-separator-padding {
height: 8px !important;
}
table[class=3Douter] .global-shrinking-to-0 {
height: 0 !important;
}
table[class=3Douter] .global-shrinking-to-10 {
height: 10px !important;
}
table[class=3Douter] .global-h1 {
font-size: 14px !important;
}

table[class=3Douter] .cut {
width: 0 !important;
padding: 0 !important;
}
table[class=3Douter] .vcut {
height: 0 !important;
padding: 0 !important;
}
table[class=3Douter] img.cut {
display: none !important;
width: 0 !important;
height: 0 !important;
}
table[class=3Douter] .cut span, table[class=3Douter] .cut a {
display: none !important;
}
table[class=3Douter] .frame {
width: 320px !important;
border-left: 0 !important;
border-right: 0 !important;
}
table[class=3Douter] .main_header.media_header {
width: 300px !important;
height: 55px !important;
}
table[class=3Douter] .header_left {
height: 55px !important;
}
table[class=3Douter] .logo_header {
height: 62px !important;
}
table[class=3Douter] .main_name {
font-size: 12px !important;
}
table[class=3Douter] .subtitle {
font-size: 12px !important;
}
table[class=3Douter] .media_main {
width: 300px !important;
}
table[class=3Douter] .media_main .intro {
width: 260px !important;
font-size: 14px !important;
}
table[class=3Douter] .media_main .intro2 {
font-size: 14px !important;
}
table[class=3Douter] .media_main .suggestions {
font-size: 14px !important;
}
table[class=3Douter] .media_more {
width: 300px !important;
border-radius: 0 !important;
background: #fff !important;
border-top: 1px solid #e8e8e8 !important;
}
table[class=3Douter] .media_button {
width: 300px !important;
background-color: #209ae4 !important;
padding-top: 3px !important;
padding-bottom: 3px !important;
}
table[class=3Douter] .media_footer {
font-size: 11px !important;
line-height: 14px !important;
padding: 0 10px !important;
}
table[class=3Douter] .address {
font-size: 11px !important;
line-height: 14px !important;
display: block !important;
}
table[class=3Douter] td[class=3Dfooter-padding-top] {
height: 12px !important;
}
table[class=3Douter] td[class=3Dfooter-padding-bottom] {
height: 17px !important;
}
table[class=3Douter] .media_footer br {
display: none !important;
}
table[class=3Douter] .spacer.ios {
display: none !important;
}
table[class=3Douter] .reset {
display: block !important;
padding-bottom: 4px !important;
}
table[class=3Douter] .media_logo_div {
display: block !important;
position: absolute !important;
left: 274px !important;
top: 0 !important;
background-image: url('https://ea.twimg.com/email/t1/ribbon.png') !importan=
t;
background-size: 100% 100% !important;
width: 36px !important;
height: 68px !important;
z-index: 1 !important;
}
table[class=3Demployee-only-padding-top-bottom] {
width: 300px !important;
}
table[class=3Demployee-only] {
width: 300px !important;
padding: 10px 0;
}
td[class=3Dheader_padding] {
height: 55px !important;
}
}

@media only screen and (min-device-width: 768px) and (max-device-width: 102=
4px) {
table[class=3Douter] .media_button {
padding-top: 3px !important;
padding-bottom: 3px !important;
background-color: #209ae4 !important;
}
table[class=3Douter] .media_button td.cut {
width: 0 !important;
padding: 0 !important;
}
table[class=3Douter] .media_button {
padding-left: 10px !important;
padding-right: 10px !important;
}
}
</style>
</head>
<body style=3D"margin: 0; padding: 0; background: #fff;-webkit-text-size-ad=
just:100%;">
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%" clas=
s=3D"outer" style=3D"position:relative;background:#ddd;">
<tbody>
<tr>
<td>
<table class=3D"inner frame" align=3D"center" cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"670" style=3D"background:#fff;position:relativ=
e;border:0;border-left:1px solid #ccc;border-right:1px solid #ccc;">
<tbody>
<tr>
<td> <a href=3D"https://twitter.com/i/redirect?url=3Dhttps%3A%2F%2Ftwitter.=
com%3Ft%3D1%26cn%3DZm9sbG93ZXI%253D%26sig%3Ddaba50b716ca3802784f2ba9a5f47d4=
;iid=3D70051d3b9b5c4e468cfedd9dfe073eba&amp;uid=3D95216089&amp;nid=3D23+21"=
 style=3D"border:none;color:#0084b4;text-decoration:none;"><span class=3D"m=
edia_logo_div"></span></a>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"670" class=
=3D"header frame" style=3D"background:#f2f2f2;table-layout:fixed;">
<tbody>
<tr>
<td class=3D"header_left cut" style=3D"width:19px;height:77px;"> &nbsp; </t=
d>
<td height=3D"94" width=3D"46" valign=3D"top" rowspan=3D"2" class=3D"logo_h=
eader cut" style=3D"background:#fff;line-height:100%;"><a href=3D"https://t=
witter.com/i/redirect?url=3Dhttps%3A%2F%2Ftwitter.com%3Ft%3D1%26cn%3DZm9sbG=
fedd9dfe073eba&amp;uid=3D95216089&amp;nid=3D23+21" style=3D"border:none;col=
or:#0084b4;text-decoration:none;"><img class=3D"logo cut" src=3D"https://ea=
.twimg.com/email/t1/ribbon.png" width=3D"46" height=3D"94" style=3D"border:=
0;line-height:100%;border:0;" /></a></td>
<td class=3D"cut" width=3D"9"> &nbsp; </td>
<td width=3D"10" height=3D"77" class=3D"header_padding"> &nbsp; </td>
<td width=3D"458" height=3D"77" class=3D"main_header media_header" style=3D=
"font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;color:#333;">
<table border=3D"0" cellpadding=3D"0" cellspacing=3D"0">
<tbody>
<tr>
<td class=3D"main_name" style=3D"font-size:14px;font-weight:bold;color:#000=
;"> <span dir=3D"ltr">Vlad,</span> </td>
</tr>
<tr>
<td class=3D"subtitle" style=3D"font-size:14px;color:#666;"> You have a new=
 follower on Twitter. </td>
</tr>
</tbody>
</table> </td>
<td width=3D"10" height=3D"77" class=3D"header_padding"> &nbsp; </td>
<td class=3D"main_avatar cut" width=3D"32" style=3D"text-align:right;"> <a =
href=3D"https://twitter.com/i/redirect?url=3Dhttps%3A%2F%2Ftwitter.com%2Fco=
22" style=3D"border:none;color:#0084b4;text-decoration:none;"><img class=3D=
"cut" src=3D"https://pbs.twimg.com/profile_images/554605440210706432/ZuvMox=
fB_reasonably_small.png" width=3D"32" height=3D"32" alt=3D"Vlad" style=3D"b=
ackground:#fff;border-radius:5px;border:0;" /></a> </td>
<td class=3D"col cut" style=3D"width:85px;"></td>
</tr>
<tr>
<td class=3D"main header_drop cut" style=3D"background:#fff;border-top:1px =
solid #ddd;font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;">&nb=
sp;</td>
<td class=3D"main header_drop cut" style=3D"background:#fff;border-top:1px =
solid #ddd;font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;">&nb=
sp;</td>
<td class=3D"main header_drop media_header" height=3D"17" style=3D"backgrou=
nd:#fff;border-top:1px solid #ddd;font-family:'Helvetica Neue', Helvetica, =
Arial, sans-serif;"><img width=3D"1" height=3D"1" style=3D"display: block;b=
order:0;" src=3D"https://twitter.com/scribe/ibis?t=3D1&amp;cn=3DZm9sbG93ZXI=
95216089&amp;nid=3D23+20" /></td>
<td class=3D"main header_drop cut" height=3D"17" colspan=3D"4" style=3D"bac=
kground:#fff;border-top:1px solid #ddd;font-family:'Helvetica Neue', Helvet=
ica, Arial, sans-serif;">&nbsp;</td>
</tr>
</tbody>
</table> </td>
<td rowspan=3D"3"></td>
</tr>
<tr>
<td class=3D"content" style=3D"background:#fff;">  <style type=3D"text/css"=
>
@media only screen and (max-device-width: 480px) {
table[class=3Douter] .recent_tweets {
border-top: 2px solid #e8e8e8;
padding-top: 8px !important;
}
table[class=3Douter] .hero_avatar {
width: 96px;
height: 96px;
}
table[class=3Douter] .fd_button, table[class=3Douter] .following {
padding-top: 3px !important;
padding-bottom: 3px !important
}
}
</style> <style type=3D"text/css">
@media only screen and (min-device-width: 768px) and (max-device-width: 102=
4px) {
table[class=3Douter] .fd_button, table[class=3Douter] .following {
padding-top: 3px !important;
padding-bottom: 3px !important
}
}
</style>
<table width=3D"670" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" class=
=3D"main frame" style=3D"background:#fff;font-family:'Helvetica Neue', Helv=
etica, Arial, sans-serif;">
<tbody>
<tr>
<td class=3D"col cut" style=3D"width:85px;"></td>
<td class=3D"media_main" width=3D"520">
<table width=3D"100%" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tbody>
<tr>
<td height=3D"22"></td>
</tr>
<tr>
<td align=3D"center">
<!-- place hero unit here --> <a href=3D"https://twitter.com/i/redirect?url=
=3Dhttps%3A%2F%2Ftwitter.com%2Fdranina73%3Ft%3D1%26cn%3DZm9sbG93ZXI%253D%26=
eba&amp;uid=3D95216089&amp;nid=3D23+1100" style=3D"border:none;color:#0084b=
4;text-decoration:none;"><img class=3D"hero_avatar" src=3D"https://pbs.twim=
g.com/profile_images/581849582453280769/PL7XRjVP_reasonably_small.png" widt=
h=3D"128" height=3D"128" style=3D"border:0;border-radius:5px;" /></a> </td>
</tr>
<tr>
<td align=3D"center" class=3D"hero_name row_pad" style=3D"padding-left:10px=
;padding-right:10px;padding-top:10px;"> <a class=3D"hero_name" href=3D"http=
s://twitter.com/i/redirect?url=3Dhttps%3A%2F%2Ftwitter.com%2Fdranina73%3Ft%=
=3D70051d3b9b5c4e468cfedd9dfe073eba&amp;uid=3D95216089&amp;nid=3D23+1120" d=
ir=3D"ltr" style=3D"border:none;color:#0084b4;text-decoration:none;color:#3=
33333;font-size:28px;font-weight:bold;font-family:'Helvetica Neue', Helveti=
ca, Arial, sans-serif;">=D0=9D=D0=B0=D0=B4=D0=B5=D0=B6=D0=B4=D0=B0 =D0=94=
=D1=80=D0=B0=D0=BD=D0=B8=D0=BD=D0=B0fS</a> </td>
</tr>
<tr>
<td align=3D"center" class=3D"hero_screen_name row_pad" style=3D"padding-le=
ft:10px;padding-right:10px;font-size:14px;font-family:'Helvetica Neue', Hel=
vetica, Arial, sans-serif;"> <a href=3D"https://twitter.com/i/redirect?url=
=3Dhttps%3A%2F%2Ftwitter.com%2Fdranina73%3Ft%3D1%26cn%3DZm9sbG93ZXI%253D%26=
eba&amp;uid=3D95216089&amp;nid=3D23+1110" class=3D"screen-name" style=3D"di=
rection:ltr;unicode-bidi:embed;border:none;color:#0084b4;text-decoration:no=
ne;">@dranina73</a> </td>
</tr>
<tr>
<td align=3D"center" class=3D"hero_bio row_pad" dir=3D"ltr" style=3D"paddin=
g-left:10px;padding-right:10px;color:#777;font-size:14px;font-style:italic;=
line-height:20px;padding-top:4px;padding-bottom:2px;font-family:'Georgia', =
'Helvetica Neue', Helvetica, Arial, sans-serif;"> I are excited about backp=
acking throughout the world </td>
</tr>
<tr>
<td align=3D"center" class=3D"hero_details row_pad" style=3D"padding-left:1=
0px;padding-right:10px;color:#777777;font-size:14px;font-family:'Helvetica =
Neue', Helvetica, Arial, sans-serif;padding-bottom:15px;"> <a href=3D"#" cl=
ass=3D"location" style=3D"border:none;color:#0084b4;text-decoration:none;co=
lor:#777777;text-decoration:none;">Tulsa OK</a> </td>
</tr>
<tr>
<td class=3D"vcut top_border" height=3D"5" style=3D"border-top:1px solid #e=
8e8e8;"></td>
</tr>
<tr>
<td height=3D"8"></td>
</tr>
<tr>
<td align=3D"center" class=3D"followed_by" style=3D"color:#777777;font-size=
:12px;font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;padding-bo=
ttom:10px;"> </td>
</tr>
<tr>
<td align=3D"center">
<table border=3D"0" cellpadding=3D"0" cellspacing=3D"0">
<tbody>
<tr>
<td>
<table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" background=3D"https=
://ea.twimg.com/email/t1/grey_background.png" class=3D"fd_button" style=3D"=
background-color:#eeeeee;border-radius:5px;border:1px solid #cccccc;padding=
:5px 0 5px 0;text-align:center;height:28px;width:1px;">
<tbody>
<tr>
<td valign=3D"middle" class=3D"button_icon" style=3D"padding-right:4px;padd=
ing-left:10px;line-height:0;color:#333333;font-size:13px;font-weight:bold;f=
ont-family:'Helvetica Neue', Helvetica, Arial, sans-serif;"><a class=3D"but=
ton_link" href=3D"https://twitter.com/i/redirect?url=3Dhttps%3A%2F%2Ftwitte=
9b5c4e468cfedd9dfe073eba&amp;uid=3D95216089&amp;nid=3D23+489" style=3D"bord=
er:none;color:#0084b4;text-decoration:none;color:#333333;font-size:13px;fon=
t-weight:bold;font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;">=
<img width=3D"18" height=3D"14" src=3D"https://ea.twimg.com/email/t1/blue_b=
ird.png" style=3D"border:0;" /></a></td>
<td class=3D"follow_button" style=3D"color:#333333;font-size:13px;font-weig=
ht:bold;font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;padding-=
right:10px;white-space:nowrap;"><a class=3D"button_link" href=3D"https://tw=
itter.com/i/redirect?url=3Dhttps%3A%2F%2Ftwitter.com%2Fintent%2Ffollow%3Fea=
f16da274167944953a402c641227&amp;iid=3D70051d3b9b5c4e468cfedd9dfe073eba&amp=
;uid=3D95216089&amp;nid=3D23+489" style=3D"border:none;color:#0084b4;text-d=
ecoration:none;color:#333333;font-size:13px;font-weight:bold;font-family:'H=
elvetica Neue', Helvetica, Arial, sans-serif;">Follow</a></td>
</tr>
</tbody>
</table> </td>
</tr>
</tbody>
</table> </td>
</tr>
<tr>
<td height=3D"15"></td>
</tr>
</tbody>
</table> </td>
<td class=3D"col cut" style=3D"width:85px;"></td>
</tr>
</tbody>
</table> </td>
</tr>
<tr>
<td>
<table bgcolor=3D"#eeeeee" border=3D"0" cellpadding=3D"0" cellspacing=3D"0"=
 width=3D"670" class=3D"frame footer" style=3D"background-color:#eee;backgr=
ound-image:url('https://ea.twimg.com/email/t1/shadow-bottom.jpg');backgroun=
d-position:top;background-repeat:repeat-x;border-top-color:#ddd;border-top-=
style:solid;border-top-width:1px;">
<tbody>
<tr>
<td colspan=3D"4" height=3D"16" class=3D"footer-padding-top"></td>
</tr>
<tr>
<td class=3D"col cut" style=3D"width:85px;"></td>
<td class=3D"footer_body media_footer" style=3D"font-family:'Helvetica Neue=
', Helvetica, Arial, sans-serif;font-size:12px;line-height:17px;color:#777;=
text-shadow:0 1px 0 #fff;">
<div>
Forgot your Twitter password?
<a class=3D"reset" href=3D"https://twitter.com/i/redirect?url=3Dhttps%3A%2F=
16089&amp;nid=3D23+24" style=3D"border:none;color:#0084b4;text-decoration:n=
one;">Get instructions on how to reset it.</a>
</div>
<div>
You can also
<a href=3D"https://twitter.com/i/u?t=3D1&amp;cn=3DZm9sbG93ZXI%3D&amp;sig=3D=
a96d092a9eb6bcaf7a9fce90448574bae86afaf4&amp;iid=3D70051d3b9b5c4e468cfedd9d=
fe073eba&amp;uid=3D95216089&amp;nid=3D23+26" style=3D"border:none;color:#00=
84b4;text-decoration:none;">unsubscribe from these emails</a>
<span class=3D"reset">or change your <a href=3D"https://twitter.com/i/redir=
ect?url=3Dhttps%3A%2F%2Ftwitter.com%2Fsettings%2Fnotifications%3Ft%3D1%26cn=
073eba&amp;uid=3D95216089&amp;nid=3D23+27" style=3D"border:none;color:#0084=
b4;text-decoration:none;">notification settings</a>. Need <a href=3D"https:=
//twitter.com/i/redirect?url=3Dhttps%3A%2F%2Fsupport.twitter.com%3Ft%3D1%26=
fe073eba&amp;uid=3D95216089&amp;nid=3D23+97" style=3D"border:none;color:#00=
84b4;text-decoration:none;">help</a>?</span>
</div>
<div class=3D"reset">
If you received this message in error and did not sign up for Twitter, clic=
k
<a href=3D"https://twitter.com/i/redirect?url=3Dhttps%3A%2F%2Ftwitter.com%2=
089&amp;nid=3D23+25" style=3D"border:none;color:#0084b4;text-decoration:non=
e;">not my account</a>.
</div>
<div>
<a href=3D"#" class=3D"address" style=3D"border:none;color:#0084b4;text-dec=
oration:none;font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;tex=
t-decoration:none;font-size:11px;line-height:17px;color:#999999;text-shadow=
:0 1px 0 #fff;">Twitter, Inc. 1355 Market St., Suite 900 <span class=3D"nob=
reak" style=3D"white-space:nowrap;">San Francisco, CA 94103</span></a>
</div> </td>
<td class=3D"col cut" style=3D"width:85px;"></td>
</tr>
<tr>
<td colspan=3D"3" class=3D"footer-padding-bottom" height=3D"25"></td>
</tr>
</tbody>
</table> </td>
</tr>
</tbody>
</table> </td>
</tr>
</tbody>
</table>
<img width=3D"1" height=3D"1" src=3D"loadimage" style=3D"border:0;" />
</body>
</html>

------=_Part_43710565_1338727258.1429678836363--
