Delivered-To: imapy-test@gmail.com
Received: by 10.216.110.7 with SMTP id t7csp302549weg;
        Tue, 24 Jul 2012 07:49:57 -0700 (PDT)
Received: by 10.180.99.196 with SMTP id es4mr7591879wib.18.1343141396955;
        Tue, 24 Jul 2012 07:49:56 -0700 (PDT)
Return-Path: <notilus-inbox@contact-everyone.fr>
Received: from smtp-out.contact-everyone.fr (smtp-out.contact-everyone.fr. [193.251.215.66])
        by mx.google.com with ESMTP id o47si20511395wee.140.2012.07.24.07.49.56;
        Tue, 24 Jul 2012 07:49:56 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of notilus-inbox@contact-everyone.fr designates 193.251.215.66 as permitted sender) client-ip=193.251.215.66;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of notilus-inbox@contact-everyone.fr designates 193.251.215.66 as permitted sender) smtp.mail=notilus-inbox@contact-everyone.fr
Received: from opceows1 (unknown [10.98.48.224])
	by mwinf8116.contact-everyone.fr (SMTP Server) with ESMTP id C61F770000F6
	for <imapy-test@gmail.com>; Tue, 24 Jul 2012 16:49:56 +0200 (CEST)
X-ME-UUID: 20120724144956811.C61F770000F6@mwinf8116.contact-everyone.fr
Message-ID: <181005592.1343141396799.JavaMail.notilus@opceows1>
From: Orange API contact <notilus-inbox@contact-everyone.fr>
Reply-To: api.contact@orange-api.net
To: VLADIMIR <imapy-test@gmail.com>
Subject: =?ISO-8859-15?Q?Orange_API_:_Annule_et_Remplace,?=
 =?ISO-8859-15?Q?_l'Op=E9ration_de_maintenance_Orang?=
 =?ISO-8859-15?Q?e_API_aura_lieu_le_jeudi_26_juill?=
 =?ISO-8859-15?Q?et_au_lieu_de_mercredi_25_juillet?=
Mime-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_368111_181110493.1343141396796"
Date: Tue, 24 Jul 2012 16:49:56 +0200 (CEST)

------=_Part_368111_181110493.1343141396796
Content-Type: text/html
Content-Transfer-Encoding: 7bit

<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /></head><body bgcolor="white" lang="FR"><div style="font-family:arial"><br/><p><p>
	<meta content="text/html; charset=iso-8859-1" http-equiv="Content-Type" />
</p>
<p>
	<title></title>
	<style type="text/css">
<!--
.Style3 {font-family: Arial, Helvetica, sans-serif}
.Style4 {color: #ff6600}
.Style5 {font-family: Arial, Helvetica, sans-serif; color: #333333; }
.Style6 {color: #333333}
.Style9 {font-family: Arial, Helvetica, sans-serif; color: #333333; font-size: 12px; }
.Style11 {font-family: Arial, Helvetica, sans-serif; font-size: 12px; }
body {
	margin-left: 30px;
}
.Style36 {color: #FF6600; font-weight: bold; }
.Style53 {font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #000000; }
.Style18 {font-size: 10px; color: #333333; }
.Style19 {color: #000000}
.Style21 {color: #FF6600; font-weight: bold; font-family: Arial, Helvetica, sans-serif; font-size: 10px; }
.Style22 {font-family: Arial, Helvetica, sans-serif; font-size: 10px; color: #000000; }
.Style55 {font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #FF6600; font-weight: bold; }
-->	</style>
</p>
<h2 align="left">
	<img alt="op&eacute;ration maintenance" height="100" src="https://emea.salesforce.com/servlet/servlet.ImageServer?id=01520000000kRlX&amp;oid=00D20000000KhCz&amp;lastMod=1280322382000" width="650" /></h2>
<table border="0" width="660">
	<tbody>
		<tr>
			<td width="183">
				<img alt="orange api support" height="131" src="https://emea.salesforce.com/servlet/servlet.ImageServer?id=01520000000kRlc&amp;oid=00D20000000KhCz&amp;lastMod=1280419212000" width="250" /></td>
			<td width="467">
				<div align="left">
					<blockquote>
						<p>
							<span class="Style9">Bonjour,</span></p>
					</blockquote>
				</div>
			</td>
		</tr>
	</tbody>
</table>
<p align="left" class="Style9">
	&nbsp;</p>
<p align="left" class="Style53">
	Dans le cadre de sa politique d&#39;am&eacute;lioration continue, Orange API proc&egrave;de &agrave; des travaux sur son infrastructure d&#39;h&eacute;bergement.<br />
	<br />
	Nous vous avons inform&eacute; qu&#39; <span class="Style6"> une interruption momentan&eacute;e de tous nos services aurait lieu le mercredi 25 juillet. </span></p>
<p align="left" class="Style55">
	Cette intervention a &eacute;t&eacute; report&eacute;e au jeudi 26 juillet de 8h &agrave; 8h30.</p>
<p align="left" class="Style53">
	Pendant ces travaux, ni le site web, ni les API ne seront accessibles.<br />
	<br />
	<span class="Style19">En cons&eacute;quence, nous vous conseillons de prendre toutes les dispositions utiles pour la continuit&eacute; op&eacute;rationnelle de vos services.</span><br />
	<br />
	<span class="Style19">Nous nous excusons par avance des r&eacute;percussions que cette coupure pourrait avoir sur votre service.</span></p>
<p align="left" class="Style11">
	<span class="Style19">L&#39;&eacute;quipe de support reste bien entendu &agrave; votre disposition pour d&#39;&eacute;ventuelles questions sur le</span> <a class="Style4" href="http://api.orange.com/index.php/forum/index/1-les-categories?lang=fr">forum</a>.</p>
<p align="left" class="Style53">
	Cordialement</p>
<p align="left" class="Style53">
	L&#39;&eacute;quipe des API d&#39;Orange</p>
<table border="0" width="657">
	<tbody>
		<tr>
			<td>
				<div align="left">
					<a align="left" class="Style5" href="http://api.orange.com/"><img alt="decouvrez orange api" border="0" height="38" src="https://emea.salesforce.com/servlet/servlet.ImageServer?id=01520000000kLBT&amp;oid=00D20000000KhCz&amp;lastMod=1280417756000" width="223" /></a></div>
			</td>
			<td>
				<div align="right">
					<a href="http://twitter.com/orangeapi"><img align="middle" alt="twitter orange api" border="0" height="47" src="https://emea.salesforce.com/servlet/servlet.ImageServer?id=01520000000kRmk&amp;oid=00D20000000KhCz&amp;lastMod=1280324926000" width="43" /></a><a href="http://www.facebook.com/pages/Orange-API/10150091023760551"><img align="middle" alt="facebook orange api" border="0" height="47" src="https://emea.salesforce.com/servlet/servlet.ImageServer?id=01520000000kRmz&amp;oid=00D20000000KhCz&amp;lastMod=1280325211000" width="43" /></a></div>
			</td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>
<table border="0" width="681">
	<tbody>
		<tr>
			<td>
				<div align="left">
					<p>
						<span class="Style3"><span class="Style18">l&#39;&eacute;quipe commerciale des API d&#39;Orange reste &agrave; votre disposition pour toute question : </span></span><span class="Style21">api.contact@orange-api.net</span><br />
						<br />
						<span class="Style22"><span class="Style6">Pour vous inscrire de la newsletter : </span><br />
						<span class="Style6">1) connectez vous au site</span> <a class="Style36" href="http:/api.orange.com">http:/api.orange.com</a><br />
						<span class="Style6">2) cliquez sur m&#39;abonner &agrave; la newsletter (en haut &agrave; droite).<br />
						<br />
						Pour vous d&eacute;sinscrire des mails :</span><br />
						<span class="Style6">contactez l&#39;&eacute;quipe Orange API :</span> <span class="Style36">api.contact@orange-api.net </span></span></p>
					<p>
						&nbsp;</p>
				</div>
			</td>
		</tr>
	</tbody>
</table>
<p align="left" class="Style3">
	_________________________________________________________________________________</p>
<p align="left" class="Style5">
	&nbsp;</p>
<h2 align="left">
	<img alt="op&eacute;ration maintenance" height="100" src="https://emea.salesforce.com/servlet/servlet.ImageServer?id=01520000000kSR9&amp;oid=00D20000000KhCz&amp;lastMod=1280421660000
" width="564" /></h2>
<table border="0" width="660">
	<tbody>
		<tr>
			<td width="183">
				<img alt="orange api support" height="131" src="https://emea.salesforce.com/servlet/servlet.ImageServer?id=01520000000kRlc&amp;oid=00D20000000KhCz&amp;lastMod=1280419212000" width="250" /></td>
			<td width="467">
				<div align="left">
					<blockquote>
						<p>
							<span class="Style9">hello,</span></p>
					</blockquote>
				</div>
			</td>
		</tr>
	</tbody>
</table>
<p align="left" class="Style9">
	&nbsp;</p>
<p align="left" class="Style53">
	To provide you with an improved service, we will be carrying out work aimed at optimising the performance of the APIs.<br />
	<br />
	We have told you that the Orange APIs will temporarily be unavailable from: <span class="Style6"> on Wednesday July 25th, 2012. </span></p>
<p align="left" class="Style55">
	This intervention was delayed from 8:00 (GMT+2) until 8:30 (GMT+2) on Thirsday July 26th, 2012.</p>
<p align="left" class="Style53">
	We apologise for any inconvenience that this may cause. It is necessary to carry out this improvement as part of our continuous effort to provide you with an excellent service.</p>
<p align="left" class="Style53">
	Consequently, we advise you to take all appropriate measures to ensure the continuity of your services.</p>
<p align="left" class="Style9">
	<span class="Style19">If you have any queries relating to this or any other issue, please contact the support team via the Orange API </span><span class="Style11"> </span><span class="Style11"><a class="Style4" href="http://api.orange.com/index.php/forum/index/1-les-categories?lang=en">forum </a></span>.</p>
<p align="left" class="Style53">
	The Orange API team</p>
<p align="left" class="Style9">
	&nbsp;</p>
<table border="0" width="657">
	<tbody>
		<tr>
			<td>
				<div align="left">
					<a align="left" class="Style5" href="http://api.orange.com/en"><img alt="decouvrez orange api" border="0" height="38" src="https://emea.salesforce.com/servlet/servlet.ImageServer?id=01520000000kSR4&amp;oid=00D20000000KhCz&amp;lastMod=1280420179000" width="215" /></a></div>
			</td>
			<td>
				<div align="right">
					<a href="http://twitter.com/orangeapi"><img align="middle" alt="twitter orange api" border="0" height="47" src="https://emea.salesforce.com/servlet/servlet.ImageServer?id=01520000000kRmk&amp;oid=00D20000000KhCz&amp;lastMod=1280324926000" width="43" /></a><a href="http://www.facebook.com/pages/Orange-API/10150091023760551"><img align="middle" alt="facebook orange api" border="0" height="47" src="https://emea.salesforce.com/servlet/servlet.ImageServer?id=01520000000kRmz&amp;oid=00D20000000KhCz&amp;lastMod=1280325211000" width="43" /></a></div>
			</td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>
<table border="0" width="681">
	<tbody>
		<tr>
			<td>
				<div align="left">
					<p>
						<span class="Style3"><span class="Style18">the Orange API team can be contacted at: </span></span><span class="Style21">api.contact@orange-api.net </span><br />
						<br />
						<span class="Style22"><span class="Style6">To subscribe to the newsletter :</span><br />
						<span class="Style6">1) log into the website</span> <a class="Style36" href="http:/api.orange.com">http:/api.orange.com</a><br />
						<span class="Style6">2) click on subscribe to the newsletter (on the top right hand corner of that page)<br />
						<br />
						To unsubscribe to the mailing :</span><br />
						<span class="Style6">please contact the Orange API team:</span> <span class="Style36">api.contact@orange-api.net </span></span></p>
				</div>
			</td>
		</tr>
	</tbody>
</table></p><br/><br/></div><img src="http://www.contact-everyone.fr.orange-business.com/notilus-call-status/StatusManagementServlet?COMMAND=SET&TRANSMITTER_NAME=DiffuseurMAIL&MSG_ID=2012097867465&SEQUENCE_ID=738&CALL_COUNT=0&RESULT=SUCCEEDED&RESUME=000|Le destinataire a lu le message" height="0" width="0" /></body></html>
------=_Part_368111_181110493.1343141396796--

