Delivered-To: imapy007@gmail.com
Received: by 10.194.12.104 with SMTP id u7csp138041wje;
        Fri, 10 Jan 2012 14:16:35 -0800 (PST)
X-Received: by 10.103.5.35 with SMTP id bt5mr134489lbd.4.1319392195152;
        Fri, 10 Jan 2012 14:16:35 -0800 (PST)
Return-Path: <random555@yandex.ru>
Received: from forward4m.mail.yandex.net (forward4m.mail.yandex.net. [37.122.138.5])
        by mx.google.com with ESMTPS id fa5si4201488lbc.100.2012.01.10.14.16.34
        for <imapy007@gmail.com>
        (version=TLSv1 cipher=RC4-SHA bits=128/128);
        Fri, 10 Jan 2012 14:16:35 -0800 (PST)
Received-SPF: pass (google.com: domain of random555@yandex.ru designates 37.122.138.5 as permitted sender) client-ip=37.122.138.5;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of random555@yandex.ru designates 37.122.138.5 as permitted sender) smtp.mail=random555@yandex.ru;
       dkim=pass header.i=@yandex.ru;
       dmarc=pass (p=NONE dis=NONE) header.from=yandex.ru
Received: from web23m.yandex.ru (web23m.yandex.ru [36.141.132.114])
    by forward4m.mail.yandex.net (Yandex) with ESMTP id 3C3EB322059B
    for <imapy007@gmail.com>; Sat, 11 Jan 2012 02:15:34 +0400 (MSK)
Received: from 127.0.0.1 (localhost [127.0.0.1])
    by web23m.yandex.ru (Yandex) with ESMTP id E2C6925B1290;
    Sat, 11 Jan 2012 02:16:33 +0400 (MSK)
Received: from masterchief2.tor.abc-defhijk.org (masterchief2.tor.abc-defhijk.org [75.104.230.115]) by web23m.yandex.ru with HTTP;
    Sat, 11 Jan 2012 02:16:33 +0400
From: =?koi8-r?B?4tXH0tnNIOHOxNLFyg==?= <random555@yandex.ru>
To: Alexandr <imapy007@gmail.com>
In-Reply-To: <52D00A4F.91102@gmail.com>
Subject: =?koi8-r?B?UmU6IPMg7u/3+e0gMjAxNCDn7+Tv7SEhIQ==?=
MIME-Version: 1.0
Message-Id: <555123456789123@web23m.yandex.ru>
X-Mailer: Yamail [ http://yandex.ru ] 5.0
Date: Sat, 11 Jan 2012 02:16:33 +0400
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=koi8-r

       gmail,    ţ   ,        gmail   ,            gmail

10.01.2012, 18:57, "Alexandr" <imapy007@gmail.com>:
>      ?
>
> On 1/10/14 3:52 PM,   wrote:
>
>>            
>> http://www.sample.us/index/abcd
>>   ?   ?
>>
>> 02.01.2012, 18:50, "Imapyima Testtestt" <imapy007@gmail.com>:
>>>    !    ,   ,         !
>>> 02.01.2012 16:26  " " <random555@yandex.ru> :
>>>>     2-     .    ,   ,  ӣ   .      ,         !
