Delivered-To: imapy123@gmail.com
Received: by 10.27.217.75 with SMTP id q12csp130619wlg;
        Fri, 1 Nov 2011 08:22:55 -0800 (PST)
X-Received: by 10.18.57.113 with SMTP id j3mr10394002pbq.163.1415377375250;
        Fri, 01 Nov 2011 08:22:55 -0800 (PST)
Return-Path: <bounces+1465057-85c4-imapy123=gmail.com@sendgrid.me>
Received: from o19837150229.outbound-mail.sendgrid.net ([118.37.120.211])
        by mx.google.com with ESMTPS id rq7si9115911pbc.51.2011.11.07.08.22.53
        for <imapy123@gmail.com>
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Nov 2011 08:22:55 -0800 (PST)
Received-SPF: pass (google.com: domain of bounces+1465057-85c4-imapy123=gmail.com@sendgrid.me designates 118.37.120.211 as permitted sender) client-ip=118.37.120.211;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of bounces+1465057-85c4-imapy123=gmail.com@sendgrid.me designates 118.37.120.211 as permitted sender) smtp.mail=bounces+1465057-85c4-imapy123=gmail.com@sendgrid.me;
       dkim=pass header.i=@sendgrid.info
Received: by filter-156.sjc1.sendgrid.net with SMTP id filter-156.18776.515CF17411
        2011-11-07 16:21:09.203210052 +0000 UTC
Received: from MTQ2NTA1Nw (unknown [10.12.13.125])
	by ismtpd-002.sjc1.sendgrid.net (SG) with HTTP id 1196b0f21cb.71e1.dd771
	for <publisher@meduza.io>; Fri, 01 Nov 2011 16:21:09 +0000 (GMT)
Content-Type: multipart/alternative;
	boundary="===============0418166671301116933=="
MIME-Version: 1.0
From: =?utf-8?b?0JjQu9GM0Y8g0JrRgNCw0YHQuNC70YzRidC40Lo=?=
	<publisher@meduza.io>
To: imapy123@gmail.com
Reply-To: publisher@meduza.io
Subject: =?UTF-8?B?TWVkdXphOiAyMCDQtNC90LXQuSDQstC80LXRgdGC0LU=?=
Message-ID: <1196b0f21cb.71e1.dd771@ismtpd-002.sjc1.sendgrid.net>
Date: Fri, 01 Nov 2011 16:21:09 +0000 (UTC)

--===============0418166671301116933==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable

Hi there,

If you're a user living outside of North America (U.S., Canada, Mexico), we=
're updating our Terms of Service to better serve you and the growing numbe=
r of Dropbox users around the world. These changes include the fact that we=
'll be providing our services (including Dropbox, Dropbox for Business, Car=
ousel, and Mailbox) to you via Dropbox Ireland starting on June 1, 2015. Pl=
ease note that none of our services or features are changing as a result of=
 this. You can read the updated terms at https://www.dropbox.com/l/eJ3aRDHS=
aGzBYDo10Aif3h/terms?text=3D1.

Have questions about these changes? Visit our Help Center[1] .

Thanks for using Dropbox!
The Dropbox Team

[1]: https://www.dropbox.com/123
--===============1642230754920957684==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w=
3.org/TR/REC-html40/loose.dtd">
<html xmlns=3D"http://www.w3.org/1999/xhtml"><head><meta content=3D"text/ht=
ml; charset=3Dutf-8" http-equiv=3D"Content-Type"><style>
        @font-face {
            font-family: "proxima_nova";
            src: url("https://www.dropbox.com/static/fonts/proximanova/prox=
ima-nova-regular.otf") format("opentype");
            font-weight: normal;
            font-style: normal;
        }
        a {
            color: #007ee6;
            text-decoration: none;
        }
        </style></head><body style=3D"padding: 0; width: 100% !important; -=
webkit-text-size-adjust: 100%; margin: 0; -ms-text-size-adjust: 100%;" marg=
inheight=3D"0" marginwidth=3D"0"><center><table cellpadding=3D"8" cellspaci=
ng=3D"0" style=3D"*width: 540px; padding: 0; width: 100% !important; backgr=
ound: #ffffff; margin: 0; background-color: #ffffff;" border=3D"0"><tr><td =
valign=3D"top">
<table cellpadding=3D"0" cellspacing=3D"0" style=3D"border-radius: 4px; -we=
bkit-border-radius: 4px; border: 1px #dceaf5 solid; -moz-border-radius: 4px=
;" border=3D"0" align=3D"center"><tr><td colspan=3D"3" height=3D"6"></td></=
tr><tr style=3D"line-height: 0px;"><td width=3D"100%" style=3D"font-size: 0=
px;" align=3D"center" height=3D"1"><img width=3D"40px" style=3D"max-height:=
 73px; width: 40px; *width: 40px; *height: 73px;" alt=3D"" src=3D"https://w=
ww.dropbox.com/static/images/emails/glyph/glyph_34@2x.png"></td></tr><tr><t=
d><table cellpadding=3D"0" cellspacing=3D"0" style=3D"line-height: 25px;" b=
order=3D"0" align=3D"center"><tr><td colspan=3D"3" height=3D"30"></td></tr>=
<tr><td width=3D"36"></td>
<td width=3D"454" align=3D"left" style=3D"color: #444444; border-collapse: =
collapse; font-size: 11pt; font-family: proxima_nova, 'Open Sans', 'Lucida =
Grande', 'Segoe UI', Arial, Verdana, 'Lucida Sans Unicode', Tahoma, 'Sans S=
erif'; max-width: 454px;" valign=3D"top">Hi there,<br><br>If you're a user =
living outside of North America (U.S., Canada, Mexico), we're updating our =
Terms of Service to better serve you and the growing number of Dropbox user=
s around the world. These changes include the fact that we'll be providing =
our services (including Dropbox, Dropbox for Business, Carousel, and Mailbo=
x) to you via Dropbox Ireland starting on June 1, 2015. Please note that no=
ne of our services or features are changing as a result of this. You can re=
ad the updated terms at https://www.dropbox.com/terms.<br><br>   Have quest=
ions about these changes? Visit our <a href=3D"https://www.dropbox.com/l/9i=
HgtW9Byn59kBzJw0nnDw/help/9063">Help Center</a>.<br><br>Thanks for using Dr=
opbox!<br>The Dropbox Team</td>
<td width=3D"36"></td>
</tr><tr><td colspan=3D"3" height=3D"36"></td></tr></table></td></tr></tabl=
e><table cellpadding=3D"0" cellspacing=3D"0" align=3D"center" border=3D"0">=
<tr><td height=3D"10"></td></tr><tr><td style=3D"padding: 0; border-collaps=
e: collapse;"><table cellpadding=3D"0" cellspacing=3D"0" align=3D"center" b=
order=3D"0"><tr style=3D"color: #a8b9c6; font-size: 11px; font-family: prox=
ima_nova, 'Open Sans', 'Lucida Grande', 'Segoe UI', Arial, Verdana, 'Lucida=
 Sans Unicode', Tahoma, 'Sans Serif'; -webkit-text-size-adjust: none;"><td =
width=3D"400" align=3D"left"></td>
<td width=3D"128" align=3D"right">&#169; 2015 Dropbox</td>
</tr></table></td></tr></table></td></tr></table></center></body></html><im=
g width=3D"1" src=3D"https://www.dropbox.com/l/PiXFvnjLe7RUZ4F5NdprqE" heig=
ht=3D"1" />
--===============1642230754920957684==--
